;
; This is the core make file that downloads dependencies of the
; OFF install profile.
;
; 
;This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.28"

; +++++ Modules +++++
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[context][subdir] = "contrib"
projects[context][version] = "3.2"

projects[context_og][subdir] = "contrib"
projects[context_og][version] = "2.1"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entityconnect][subdir] = "contrib"
projects[entityconnect][version] = "1.0-rc1"

projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc7"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.5"

projects[og][subdir] = "contrib"
projects[og][version] = "2.7"

projects[pathologic][subdir] = "contrib"
projects[pathologic][version] = "2.12"

projects[realname][subdir] = "contrib"
projects[realname][version] = "1.2"

projects[session_api][subdir] = "contrib"
projects[session_api][version] = "1.0-rc1"

projects[stringoverrides][subdir] = "contrib"
projects[stringoverrides][version] = "1.8"

; +++++ Custom +++++
projects[integration][download][type] = "git"
projects[integration][download][url] = "git@github.com:rafaqz/integration"
projects[integration][type] = "module"
;projects[integration][version] = "1.0-alpha1"
projects[integration][subdir] = "custom"

; +++++ Features +++++
projects[basic_page_feature][download][type] = "git"
projects[basic_page_feature][download][url] = "git@github.com:rafaqz/basic_page_feature"
projects[basic_page_feature][type] = "module"
projects[basic_page_feature][subdir] = "features"

projects[blog_feature][download][type] = "git"
projects[blog_feature][download][url] = "git@github.com:rafaqz/blog_feature"
projects[blog_feature][type] = "module"
projects[blog_feature][subdir] = "features"

projects[bugherd_feature][download][type] = "git"
projects[bugherd_feature][download][url] = "git@github.com:rafaqz/bugherd_feature"
projects[bugherd_feature][type] = "module"
projects[bugherd_feature][subdir] = "features"

projects[conversation_feature][download][type] = "git"
projects[conversation_feature][download][url] = "git@github.com:rafaqz/conversation_feature"
projects[conversation_feature][download][branch] = "off"
projects[conversation_feature][type] = "module"
projects[conversation_feature][subdir] = "features"

projects[core_feature][download][type] = "git"
projects[core_feature][download][url] = "git@github.com:rafaqz/core_feature"
projects[core_feature][type] = "module"
projects[core_feature][subdir] = "features"

projects[featured_feature][download][type] = "git"
projects[featured_feature][download][url] = "git@github.com:rafaqz/featured_feature"
projects[featured_feature][type] = "module"
projects[featured_feature][subdir] = "features"

projects[formats_feature][download][type] = "git"
projects[formats_feature][download][url] = "git@github.com:rafaqz/formats_feature"
projects[formats_feature][type] = "module"
projects[formats_feature][subdir] = "features"

projects[front_icons_feature][download][type] = "git"
projects[front_icons_feature][download][url] = "git@github.com:rafaqz/front_icons_feature"
projects[front_icons_feature][type] = "module"
projects[front_icons_feature][subdir] = "features"

projects[groups_feature][download][type] = "git"
projects[groups_feature][download][url] = "git@github.com:rafaqz/groups_feature"
projects[groups_feature][type] = "module"
projects[groups_feature][download][branch] = "off"
projects[groups_feature][subdir] = "features"

projects[idea_feature][download][type] = "git"
projects[idea_feature][download][url] = "git@github.com:rafaqz/idea_feature"
projects[idea_feature][type] = "module"
projects[idea_feature][subdir] = "features"

projects[image_feature][download][type] = "git"
projects[image_feature][download][url] = "git@github.com:rafaqz/image_feature"
projects[image_feature][type] = "module"
projects[image_feature][subdir] = "features"

projects[knowledge_feature][download][type] = "git"
projects[knowledge_feature][download][url] = "git@github.com:rafaqz/knowledge_feature"
projects[knowledge_feature][type] = "module"
projects[knowledge_feature][subdir] = "features"

projects[login_feature][download][type] = "git"
projects[login_feature][download][url] = "git@github.com:rafaqz/login_feature.git"
projects[login_feature][type] = "module"
projects[login_feature][subdir] = "features"

projects[mail_feature][download][type] = "git"
projects[mail_feature][download][url] = "git@github.com:rafaqz/mail_feature"
projects[mail_feature][type] = "module"
projects[mail_feature][download][branch] = "off"
projects[mail_feature][subdir] = "features"

;projects[mail_reply_feature][download][type] = "git"
;projects[mail_reply_feature][download][url] = "git@github.com:rafaqz/mail_reply_feature"
;projects[mail_reply_feature][type] = "module"
;projects[mail_reply_feature][subdir] = "features"

projects[membership_form_feature][download][type] = "git"
projects[membership_form_feature][download][url] = "git@github.com:rafaqz/membership_form_feature"
projects[membership_form_feature][type] = "module"
projects[membership_form_feature][subdir] = "features"

projects[message_feature][download][type] = "git"
projects[message_feature][download][url] = "git@github.com:rafaqz/message_feature.git"
projects[message_feature][download][branch] = "off"
projects[message_feature][type] = "module"
projects[message_feature][subdir] = "features"

projects[news_feature][download][type] = "git"
projects[news_feature][download][url] = "git@github.com:rafaqz/news_feature"
projects[news_feature][type] = "module"
projects[news_feature][subdir] = "features"

projects[performance_feature][download][type] = "git"
projects[performance_feature][download][url] = "git@github.com:rafaqz/performance_feature"
projects[performance_feature][type] = "module"
projects[performance_feature][subdir] = "features"

projects[profile_feature][download][type] = "git"
projects[profile_feature][download][url] = "git@github.com:rafaqz/profile_feature"
projects[profile_feature][download][branch] = "off"
projects[profile_feature][type] = "module"
projects[profile_feature][subdir] = "features"

projects[projects_feature][download][type] = "git"
projects[projects_feature][download][url] = "git@github.com:rafaqz/projects_feature"
projects[projects_feature][type] = "module"
projects[projects_feature][subdir] = "features"

;projects[search_feature][download][type] = "git"
;projects[search_feature][download][url] = "git@github.com:rafaqz/search_feature"
;projects[search_feature][type] = "module"
;;projects[search_feature][version] = "1.0-alpha1"
;projects[search_feature][subdir] = "features"

projects[spam_feature][download][type] = "git"
projects[spam_feature][download][url] = "git@github.com:rafaqz/spam_feature"
projects[spam_feature][type] = "module"
projects[spam_feature][subdir] = "features"
projects[document_feature][download][type] = "git"
projects[document_feature][download][url] = "git@github.com:rafaqz/document_feature"
projects[document_feature][type] = "module"
projects[document_feature][subdir] = "features"
projects[header_feature][download][type] = "git"
projects[header_feature][download][url] = "git@github.com:rafaqz/header_feature"
projects[header_feature][type] = "module"
projects[header_feature][subdir] = "features"

projects[tags_feature][download][type] = "git"
projects[tags_feature][download][url] = "git@github.com:rafaqz/tags_feature"
projects[tags_feature][type] = "module"
projects[tags_feature][subdir] = "features"

projects[tag_filter_feature][download][type] = "git"
projects[tag_filter_feature][download][url] = "git@github.com:rafaqz/tag_filter_feature"
projects[tag_filter_feature][type] = "module"
projects[tag_filter_feature][subdir] = "features"

projects[off_layout_feature][download][type] = "git"
projects[off_layout_feature][download][url] = "git@github.com:rafaqz/off_layout_feature.git"
projects[off_layout_feature][type] = "module"
projects[off_layout_feature][subdir] = "features"

; +++++ Themes +++++
projects[zurb-foundation][version]= "4.0-beta2"
projects[zurb-foundation][type] = "theme"

projects[custom_zurb][download][type] = "git"
projects[custom_zurb][download][url] = "git@github.com:rafaqz/custom_zurb.git"
projects[custom_zurb][type] = "theme"

; +++++ Libraries +++++
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.2/ckeditor_4.2_standard.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "modules/contrib/ckeditor"
libraries[ckeditor][overwrite] = TRUE
libraries[ckeditor][type] = "library"

